apiVersion: v1
kind: Secret
metadata:
  name: tastmanagement-secret
  namespace: tastmanagement
type: Opaque
data:
  # Base64 encoded values
  # postgres password: postgres (base64: cG9zdGdyZXM=)
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # Django secret key (you should generate a new one)
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLSQqQCheZil3NjcldGxpLXk0YXhqcF9kXnB5MDBsKTI0Xl43Y3JqKyVpJHFiIXojOXcx
